import shutil
import subprocess
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class StaticStructureTests(unittest.TestCase):
    def test_health_uses_shared_service(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        routes = (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8')
        self.assertIn('from api.service import', flask_server)
        self.assertIn('resolve_get_route', builtin_server)
        self.assertIn("'/api/health'", routes)
        self.assertIn('health_payload', routes)

    def test_vercel_routes_are_unified_through_index(self):
        routes = (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8')
        vercel = (ROOT / 'vercel.json').read_text(encoding='utf-8')
        self.assertFalse((ROOT / 'api' / 'users.py').exists())
        self.assertFalse((ROOT / 'api' / 'state.py').exists())
        self.assertFalse((ROOT / 'api' / 'health.py').exists())
        self.assertIn('/api/(.*)', vercel)
        self.assertIn('/api/index.py', vercel)
        self.assertIn('/api/users', routes)
        self.assertIn('user_action_payload', routes)

    def test_environment_details_are_not_exposed_by_health_route(self):
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertNotIn('get_environment_status', service)

    def test_session_secret_is_not_hardcoded(self):
        storage = (ROOT / 'api' / 'storage.py').read_text(encoding='utf-8')
        environment = (ROOT / 'docs' / 'ENVIRONMENT.md').read_text(encoding='utf-8')
        self.assertNotIn('DEFAULT_SESSION_SECRET', storage)
        self.assertNotIn('app-default', storage)
        self.assertIn('APP_SESSION_SECRET', environment)
        self.assertIn('OPENAI_API_KEY', environment)

    def test_configurable_text_is_sanitized(self):
        shared = (ROOT / 'js' / 'shared.js').read_text(encoding='utf-8')
        self.assertIn('sanitizePlainText', shared)
        self.assertIn('merged.moduleLabels = sanitizeMap', shared)
        self.assertIn('merged.moduleIcons = sanitizeMap', shared)

    def test_large_view_is_outside_index(self):
        index = (ROOT / 'index.html').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        loader = (ROOT / 'js' / 'view-loader.js').read_text(encoding='utf-8')
        self.assertNotIn('ordersView', index)
        self.assertIn('ordersView', view)
        self.assertIn('APP_ASSET_VERSION', loader)
        self.assertIn('views/app-shell.html?v=', loader)
        self.assertIn("import(`./main.js?v=", loader)
        self.assertIn('js/view-loader.js?v=', index)
        self.assertNotIn('innerHTML', loader)

    def test_frontend_modules_parse_before_login(self):
        if not shutil.which('node'):
            self.skipTest('node is not available')
        for path in sorted((ROOT / 'js').rglob('*.js')):
            result = subprocess.run(
                ['node', '--input-type=module', '--check'],
                input=path.read_bytes(),
                capture_output=True,
            )
            self.assertEqual(result.returncode, 0, f'{path}\n{result.stderr.decode("utf-8", "replace")}')

    def test_trip_route_ui_has_readable_labels(self):
        trips_ui = (ROOT / 'js' / 'trips' / 'ui.js').read_text(encoding='utf-8')
        for text in ('候選路線數', '建議順序', '預估時間', '預估距離', '用 Google Maps 開啟', '固定點', '上移', '下移'):
            self.assertIn(text, trips_ui)
        self.assertIn('formatDistance', trips_ui)
        self.assertIn('公里', trips_ui)
        self.assertNotIn('totalDistanceM)} m', trips_ui)
        for broken in ('嚗', '撠', '蝮', '銝', '', '?strong', '??'):
            self.assertNotIn(broken, trips_ui)

    def test_trip_factory_uses_the_registered_address(self):
        constants = (ROOT / 'js' / 'trips' / 'constants.js').read_text(encoding='utf-8')
        shared = (ROOT / 'js' / 'shared.js').read_text(encoding='utf-8')
        self.assertIn("address: '新北市中和區立言街53號'", constants)
        self.assertIn('lat: 25.0118144', constants)
        self.assertIn('lng: 121.4775296', constants)
        self.assertIn("address: '新北市中和區立言街53號'", shared)
        self.assertNotIn('121.4982', constants)

    def test_scalable_data_routes_exist_in_both_servers(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        routes = (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8')
        for route in ('/api/bootstrap', '/api/data/', '/api/changes', '/api/reports/summary', '/api/orders/recognize', '/api/orders/recognize/status', '/api/orders/recognize/corrections'):
            if route == '/api/data/':
                self.assertIn(route, flask_server)
                self.assertIn(route, builtin_server)
            else:
                self.assertIn(route, routes)
        self.assertIn('GET_ROUTES', routes)
        self.assertIn('POST_ROUTES', routes)

    def test_line_notification_and_reply_integration_exists(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        routes = (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8')
        line_bot = (ROOT / 'api' / 'line_bot.py').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        notifications = (ROOT / 'js' / 'notifications.js').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        docs = (ROOT / 'docs' / 'ENVIRONMENT.md').read_text(encoding='utf-8')
        self.assertIn('/api/line/webhook', flask_server)
        self.assertIn('/api/line/webhook', builtin_server)
        self.assertIn('/api/line/status', routes)
        self.assertIn('/api/line/push', routes)
        self.assertIn('X-Line-Signature', flask_server)
        self.assertIn('LINE_CHANNEL_SECRET', line_bot)
        self.assertIn('LINE_CHANNEL_ACCESS_TOKEN', line_bot)
        self.assertIn('hmac.compare_digest', line_bot)
        self.assertIn('lineDestinations', line_bot)
        self.assertIn('lineWebhookUrl', view)
        self.assertIn('/api/line/status', notifications)
        self.assertIn('/api/line/push', notifications)
        self.assertIn('/api/line/push', finance)
        self.assertIn('/api/line/push', main)
        self.assertNotIn('line.me/R/msg/text', finance)
        self.assertIn('https://www.sanqingco.com/api/line/webhook', docs)

    def test_admin_clear_test_data_route_exists(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        routes = (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        self.assertIn('/api/admin/clear-test-data', routes)
        self.assertIn('resolve_post_route', flask_server)
        self.assertIn('resolve_post_route', builtin_server)
        self.assertIn('/api/admin/clear-test-data', settings)
        self.assertIn('clearTestDataBtn', view)

    def test_backup_restore_routes_and_controls_exist(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        routes = (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        for route in ('/api/admin/backup', '/api/admin/restore'):
            self.assertIn(route, routes)
            self.assertIn(route, settings)
        self.assertIn('resolve_get_route', flask_server)
        self.assertIn('resolve_post_route', builtin_server)
        self.assertIn('downloadBackupBtn', view)
        self.assertIn('restoreBackupFile', view)
        self.assertIn('restoreBackupBtn', view)

    def test_capacity_monitor_exists(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        routes = (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('/api/admin/capacity', routes)
        self.assertIn('resolve_get_route', flask_server)
        self.assertIn('resolve_get_route', builtin_server)
        self.assertIn('capacity_payload', service)
        self.assertIn('refreshCapacityBtn', view)
        self.assertIn('capacityMetrics', view)
        self.assertIn('/api/admin/capacity', settings)

    def test_frontend_uses_paged_incremental_storage(self):
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn('pageSize=100', store)
        self.assertIn('/api/changes', store)
        self.assertIn("localStorage.setItem('uiSettings'", store)
        self.assertNotIn("localStorage.setItem('orders'", store)

    def test_login_does_not_wait_for_all_entity_pages(self):
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        self.assertIn('hydrateBootstrap', store)
        self.assertIn('initialPages', store)
        self.assertIn('loadEntityPagesInBackground(missingKeys)', store)
        self.assertIn('bootstrap: data.bootstrap', main)
        self.assertIn('concurrency=2', store)
        self.assertNotIn('await Promise.all(keys.map', store)

    def test_login_submit_is_guarded_against_double_clicks(self):
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        self.assertIn('let loginInFlight = false', main)
        self.assertIn('if (loginInFlight) return', main)
        self.assertIn('setLoginBusy(true)', main)
        self.assertIn('const attemptId = ++loginAttemptId', main)
        self.assertIn('resetAuthenticatedSync()', main)
        self.assertIn('js/main.js?v=', view)

    def test_refresh_renders_only_the_active_view(self):
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        render_all = main[main.index('function renderAll()'):main.index('function showView(id)')]
        self.assertIn('switch (activeViewId)', render_all)
        self.assertNotIn('\n  renderDashboard();', render_all)
        self.assertNotIn('\n  renderCustomers(state);', render_all)
        self.assertNotIn('\n  renderSettings(state);', render_all)

    def test_customer_tax_id_is_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        customers = (ROOT / 'js' / 'customers.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        self.assertIn('customerTaxId', view)
        self.assertIn('搜尋名稱/統編/電話/地址', view)
        self.assertIn('normalizeTaxId', customers)
        self.assertIn('taxId = normalizeTaxId', customers)
        self.assertIn('c.taxId ||', customers)
        self.assertIn('normalizeCustomerRole', customers)
        self.assertIn("role === '客人' ? '兩者' : role", customers)
        self.assertIn("const items = ['兩者', '上游', '下游']", customers)
        self.assertIn('const billingAndUpstream', customers)
        self.assertIn("['上游', '兩者'].includes(normalizeCustomerRole(c.role))", customers)
        self.assertNotIn("['上游', '客人', '兩者'].includes(c.role)", customers)
        self.assertIn("const upstream = $('upstreamOptions')", customers)
        self.assertIn('billingAndUpstream.forEach((c) => upstream.append', customers)
        self.assertIn('billingAndUpstream.forEach((c) => billing.append', customers)
        self.assertIn("taxId:String(c.taxId??'')", store)
        self.assertIn('invoiceBuyerTaxId', finance)
        self.assertIn('customer?.taxId', finance)

    def test_dashboard_is_compact_and_actionable(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        self.assertEqual(view.count('data-dashboard-target'), 3)
        self.assertNotIn('dashboardSmartTip', view)
        self.assertNotIn('dashboardHeroTitle', view)
        self.assertIn('summaries = {', main)
        dashboard_block = main[main.index('function renderDashboard()'):main.index('function renderAll()')]
        self.assertNotIn('formatDashboardMoney', dashboard_block)
        self.assertNotIn('NT$', dashboard_block)
        self.assertIn('pendingReceivables', dashboard_block)
        self.assertIn('pendingPayables', dashboard_block)
        self.assertIn("priority.dataset.dashboardTarget === 'financeView'", main)
        self.assertIn('.dashboard-module-grid { grid-template-columns: repeat(2', styles)

    def test_user_entered_tables_avoid_raw_inner_html(self):
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        customers = (ROOT / 'js' / 'customers.js').read_text(encoding='utf-8')
        self.assertIn('grid.replaceChildren', main)
        self.assertNotIn('grid.innerHTML', main)
        self.assertIn('body.replaceChildren()', customers)
        self.assertIn('td.textContent = value', customers)
        self.assertNotIn('tr.innerHTML = `', customers)

    def test_order_pricing_helpers_are_split_out(self):
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        ai_ui = (ROOT / 'js' / 'orders-ai.js').read_text(encoding='utf-8')
        pricing_ui = (ROOT / 'js' / 'orders-pricing.js').read_text(encoding='utf-8')
        self.assertIn("from './orders-pricing.js'", orders)
        self.assertIn('export function pricingTierLabel', pricing_ui)
        self.assertIn('export function isCustomerTierPriceRule', pricing_ui)
        self.assertLess(len(orders.splitlines()), 1095)

    def test_admin_security_forms_are_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        storage = (ROOT / 'api' / 'storage.py').read_text(encoding='utf-8')
        self.assertIn('createAccountForm', view)
        self.assertIn('financePasswordForm', view)
        self.assertIn('accountPermissionsList', view)
        self.assertIn('value="driver"', view)
        self.assertIn("action: 'create_account'", settings)
        self.assertIn("action: 'update_account_permissions'", settings)
        self.assertIn("action: 'change_finance_password'", settings)
        self.assertIn('allowedViews', settings)
        self.assertIn('allowedViews', storage)
        self.assertIn("hash_password(value)", storage)
        self.assertNotIn('e.currentTarget.reset()', settings)
        settings_close = view.index('</form>', view.index('id="settingsForm"'))
        self.assertGreater(view.index('id="createAccountForm"'), settings_close)
        self.assertGreater(view.index('id="financePasswordForm"'), settings_close)

    def test_dashboard_only_renders_modules_allowed_for_account(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn("isModuleEnabled(module.id) && hasViewPermission(module.id)", main)
        self.assertIn('id="dashboardPriorities"', view)
        self.assertIn("state.userRole === 'driver'", main)
        self.assertIn("state.userRole !== 'admin'", main)
        self.assertIn("!state.allowedViews.includes('notificationsView')", store)

    def test_trip_accounts_load_read_only_order_dependencies(self):
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn("driver:['customers','orders']", store)
        self.assertIn("tripsView:['customers','orders']", store)
        self.assertIn('account_can_read_entity', service)
        self.assertIn("entity in {'orders','customers'} and account_can_view(account,'tripsView')", service)
        self.assertIn('require_entity_read_access(token,entity)', service)

    def test_trip_execute_is_next_to_manual_confirmation_and_marks_orders_sent(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        trips = (ROOT / 'js' / 'trips.js').read_text(encoding='utf-8')
        routes = (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8')
        order_pool = view[view.index('id="tripOrderPoolCard"'):view.index('id="tripRouteCard"')]
        route_card = view[view.index('id="tripRouteCard"'):view.index('</section>', view.index('id="tripRouteCard"'))]
        self.assertNotIn('id="tripOptimizeBtn"', order_pool)
        self.assertNotIn('id="tripExecuteBtn"', order_pool)
        self.assertIn('id="tripOptimizeBtn"', route_card)
        self.assertIn('id="tripExecuteBtn"', route_card)
        self.assertLess(route_card.index('id="tripOptimizeBtn"'), route_card.index('id="tripConfirmManualBtn"'))
        self.assertLess(route_card.index('id="tripConfirmManualBtn"'), route_card.index('id="tripExecuteBtn"'))
        self.assertIn("fetch('/api/trips/execute'", trips)
        self.assertIn("textContent = '執行中…'", trips)
        self.assertIn("function canExecuteOrder(order)", trips)
        self.assertIn('return state.orders.filter(canExecuteOrder);', trips)
        self.assertIn('目前沒有尚未送出的工單', trips)
        self.assertIn("已完成」的工單後再執行車趟。已送出的工單不能重複送出", trips)
        self.assertNotIn("${status}（不可執行）", trips)
        self.assertIn("'/api/trips/execute'", routes)

    def test_module_settings_use_two_level_navigation(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        self.assertIn('id="settingsBrandDisclosure"', view)
        self.assertIn('class="settings-disclosure-summary"', view)
        self.assertIn('settings-disclosure-card', styles)
        self.assertLess(view.index('id="settingsBrandDisclosure"'), view.index('id="settingsAppTitle"'))
        self.assertIn('id="settingsModuleDetail"', view)
        self.assertIn('id="settingsModulesBack"', view)
        self.assertIn('data-settings-internal-module="ordersView"', view)
        self.assertIn('data-settings-internal-module="customersView"', view)
        self.assertIn('data-settings-internal-module="tripsView"', view)
        self.assertIn('data-settings-internal-module="financeView"', view)
        self.assertIn('data-settings-internal-module="inventoryView"', view)
        self.assertIn('data-settings-open-module', settings)
        self.assertIn('renderModuleSettingsNavigator', settings)
        self.assertIn('MODULES_WITH_INTERNAL_SETTINGS', settings)
        self.assertLess(view.index('data-settings-internal-module="ordersView"'), view.index('id="settingsOrderWarningDays"'))
        self.assertLess(view.index('data-settings-internal-module="financeView"'), view.index('id="settingsReceivableOverdueDays"'))
        self.assertLess(view.index('data-settings-internal-module="inventoryView"'), view.index('id="settingsInventoryLowStockDefault"'))
        self.assertIn('.settings-module-nav-card', styles)

    def test_finance_quick_actions_are_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        self.assertIn('financeReceivableActions', view)
        self.assertIn('financePayableActions', view)
        self.assertIn('data-finance-receivable-done', finance)
        self.assertIn('data-finance-payable-done', finance)
        self.assertIn('escapeHtml(value)', finance)
        self.assertIn('.table-actions', styles)

    def test_finance_home_is_progressively_disclosed(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        self.assertIn('data-finance-screen="concerns"', view)
        self.assertIn('data-finance-screen="entry"', view)
        self.assertIn('財經重點', view)
        self.assertIn('getFinanceConcernCount', finance)
        self.assertIn('ensureFinanceOverview', finance)
        self.assertIn('applyFinanceScreen', finance)
        self.assertIn("entry.id = 'financeEntryScreen'", finance)
        self.assertIn("state.financeScreen = 'main'", (ROOT / 'js' / 'main.js').read_text(encoding='utf-8'))
        self.assertIn('.finance-overview-actions', styles)
        self.assertIn('.finance-action-card', styles)

    def test_finance_month_close_and_statement_are_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        self.assertIn('financeCloseMonth', view)
        self.assertIn('statementCustomer', view)
        self.assertIn('exportMonthCloseBtn', view)
        self.assertIn('printCustomerStatementBtn', view)
        self.assertIn('getMonthCloseData', finance)
        self.assertIn('exportCustomerStatement', finance)

    def test_customer_price_rules_are_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        records = (ROOT / 'api' / 'records.py').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('priceRuleForm', view)
        self.assertIn('data-order-screen="pricing"', view)
        self.assertIn('openPriceRulesFromOrderBtn', view)
        self.assertIn('priceRuleCustomerMatches', view)
        self.assertNotIn('side-btn" type="button" data-order-screen="pricing"', view)
        self.assertIn('data-order-screen="form">返回新增工單', view)
        self.assertIn('id="priceRuleMatrix"', view)
        self.assertIn('data-price-tier="BIG"', view)
        self.assertIn('data-price-tier="REGULAR"', view)
        self.assertIn('data-price-tier="SMALL"', view)
        self.assertIn('id="priceRuleBounds"', view)
        self.assertIn('data-price-bound-tier="SMALL"', view)
        self.assertIn('data-price-bound-edge="shortMin"', view)
        self.assertIn('data-price-bound-edge="longMax"', view)
        self.assertIn('ordersPricingScreen', view)
        self.assertNotIn('data-finance-screen="pricing"', view)
        self.assertNotIn('financePricingScreen', view)
        self.assertIn('priceRulesTbody', view)
        self.assertIn('.pricing-matrix', (ROOT / 'styles.css').read_text(encoding='utf-8'))
        self.assertIn('.pricing-bounds', (ROOT / 'styles.css').read_text(encoding='utf-8'))
        orders_block = view[view.index('id="ordersView"'):view.index('id="customersView"')]
        finance_block = view[view.index('id="financeView"'):view.index('id="auditView"')]
        self.assertIn('priceRuleForm', orders_block)
        self.assertNotIn('priceRuleForm', finance_block)
        self.assertIn('buildPriceRulesFromForm', orders)
        self.assertIn('isCustomerTierPriceRule', orders)
        self.assertIn('isCustomerPricingConfigRule', orders)
        self.assertIn('getPriceRuleCustomerMatches', orders)
        self.assertIn('data-price-rule-customer', orders)
        self.assertIn('customer.taxId', orders)
        self.assertIn("['glossType']", orders)
        self.assertIn("'其他'", orders)
        self.assertIn("'其他'", store)
        self.assertIn("activeScreen !== 'pricing'", orders)
        self.assertIn('data-edit-price-rule', orders)
        self.assertNotIn('buildPriceRulesFromForm', finance)
        self.assertIn('calculateOrderQuote', orders)
        self.assertIn('pricingMode', orders)
        self.assertIn('id="machineType"', view)
        self.assertIn('客人價格表', view)
        self.assertIn('小台（單張價）', view)
        self.assertIn('value="REGULAR">常規', view)
        self.assertIn('級距判斷', view)
        self.assertIn('計價公式', view)
        self.assertIn('超過常規上限就是大台', view)
        self.assertIn('settingsPricingSmallShortMax', view)
        self.assertIn('settingsPricingSmallLongMax', view)
        self.assertIn('settingsPricingRegularShortMax', view)
        self.assertIn('settingsPricingRegularLongMax', view)
        self.assertIn('settingsPricingRegularPva', view)
        self.assertIn('settingsPricingSmallPva', view)
        self.assertIn('tierPrices', (ROOT / 'js' / 'shared.js').read_text(encoding='utf-8'))
        self.assertIn('dimensionThresholds', (ROOT / 'js' / 'shared.js').read_text(encoding='utf-8'))
        self.assertIn('settingsPricingDivisor', view)
        self.assertIn('settingsPricingBigMinimum', view)
        self.assertNotIn('id="newGlossType"', view)
        self.assertNotIn('id="addGlossBtn"', view)
        self.assertNotIn("$('addGlossBtn')", orders)
        self.assertIn('customer-price-row', view)
        self.assertIn('populatePriceRuleFromOrder', orders)
        self.assertIn('updatePriceRuleFormulaPreview', orders)
        self.assertIn('priceRuleFormulaText', view)
        self.assertIn('priceRuleCalculatedPrice', view)
        self.assertIn('priceRuleFinalPrice', view)
        self.assertIn("priceRules:'priceRules'", store)
        self.assertIn("'priceRules': 'priceRules'", records)
        self.assertIn("'priceRules':'ordersView'", service)
        self.assertIn('pricing_quote_payload', service)
        self.assertIn('/api/pricing/quote', (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8'))

    def test_ai_correction_center_is_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('aiCorrectionsTbody', view)
        self.assertIn('refreshAiCorrectionsBtn', view)
        self.assertIn('/api/data/aiCorrections', orders)
        self.assertIn('exportAiCorrections', orders)
        self.assertIn("'aiCorrections':'ordersView'", service)

    def test_ai_order_tools_can_be_disabled_from_settings(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        shared = (ROOT / 'js' / 'shared.js').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        self.assertIn('id="settingsOrderShowAiTools"', view)
        self.assertIn('id="aiOrderRecognizer"', view)
        self.assertIn('id="aiCorrectionCenter"', view)
        self.assertIn('showAiTools: true', shared)
        self.assertIn("showAiTools: !!$('settingsOrderShowAiTools')?.checked", settings)
        self.assertIn("orderSettings.showAiTools === false", orders)
        self.assertIn("getOrderModuleSettings(state).showAiTools === false", orders)

    def test_order_list_has_compact_responsive_layout(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn('id="ordersListSummary"', view)
        self.assertIn('class="orders-table"', view)
        self.assertIn('<th>工單單號</th><th>交貨日期</th><th>狀態</th><th>操作</th>', view)
        order_list_view = view[view.index('id="ordersListScreen"'):view.index('id="ordersFormScreen"')]
        self.assertNotIn('<th>客人</th>', order_list_view)
        self.assertIn('order-preview-row', orders)
        self.assertIn("tr.style.setProperty('--row-index'", orders)
        self.assertIn('data-label="工單單號"', orders)
        render_block = orders[orders.index('export function renderOrders'):orders.index('export function clearOrderForm')]
        self.assertNotIn('data-label="客人"', render_block)
        self.assertNotIn('order-preview-customer', render_block)
        self.assertIn('colspan="4"', render_block)
        self.assertIn('data-copy-order', orders)
        self.assertIn('雙擊複製', orders)
        self.assertIn('data-quick-status="已送出"', orders)
        self.assertIn('data-quick-status="已完成"', orders)
        self.assertIn("settings.quickActions?.['已送出'] !== false", orders)
        self.assertIn("order.status === '已送出'", orders)
        self.assertNotIn('class="order-price-cell">NT$', orders)
        self.assertIn('order-status-badge', orders)
        self.assertIn('.order-row-actions .order-sent-action', styles)
        self.assertIn('@keyframes orderRowEnter', styles)
        self.assertIn('@keyframes orderRowComplete', styles)
        self.assertIn('.orders-table { min-width: 560px; table-layout: fixed; }', styles)
        self.assertIn('.orders-table thead { display: table-header-group; }', styles)
        self.assertIn('const displayTotal=', store)

    def test_navigation_and_order_list_have_light_motion(self):
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        self.assertIn("panel.classList.add('view-entering')", main)
        self.assertIn('function applyViewMotion()', main)
        self.assertIn("item.classList.add('motion-item')", main)
        self.assertIn('@keyframes viewEnter', styles)
        self.assertIn('@keyframes softItemEnter', styles)
        self.assertIn('prefers-reduced-motion: reduce', styles)
        self.assertIn('highlightedOrderId = order.id', orders)
        self.assertIn('is-just-completed', orders)
        self.assertIn('pendingOrderMove = movement', orders)
        self.assertIn('order-moving-up', orders)
        self.assertIn('@keyframes orderMoveFromBelow', styles)
        self.assertIn('@keyframes orderMoveFromAbove', styles)

    def test_completing_an_order_opens_the_print_view(self):
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        self.assertIn("quickBtn.dataset.quickStatus === '已完成'", orders)
        self.assertIn('if (shouldPrint) openOrderExportWindowFromModule(order);', orders)

    def test_orders_can_be_deleted_and_enter_moves_between_fields(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('data-delete-order', orders)
        self.assertIn('確定要刪除工單', orders)
        self.assertIn("receivable.source === 'auto-order'", orders)
        self.assertIn('id="saveOrderBtn"', view)
        self.assertIn('ORDER_ENTRY_FIELD_IDS', orders)
        self.assertIn('bindOrderEnterNavigation', orders)
        self.assertIn("event.key !== 'Enter'", orders)
        self.assertIn('event.isComposing', orders)
        self.assertIn("linked_receivables", service)

    def test_order_size_notation_supports_tai_inches_and_configurable_presets(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        pricing = (ROOT / 'js' / 'pricing.js').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        self.assertIn('id="sizeNotation"', view)
        self.assertIn('id="settingsPricingSizePresets"', view)
        self.assertIn('parseSizeNotation', pricing)
        self.assertIn('台寸', pricing)
        self.assertIn('橘', pricing)
        self.assertIn("from './size-notation.js'", orders)
        self.assertIn('applySizeNotation', (ROOT / 'js' / 'size-notation.js').read_text(encoding='utf-8'))
        self.assertIn('sizeNotation:', orders)
        self.assertIn('settingsPricingSizePresets', settings)

    def test_order_preview_rows_open_for_edit(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn('使用「上移／下移」調整順序', view)
        self.assertIn("e.target.closest('[data-copy-order], [data-order-move], button') ? null", orders)
        self.assertIn("e.target.closest('tr[data-edit]')", orders)
        self.assertIn('openOrderForEdit(state, row.dataset.edit)', orders)
        self.assertIn("sortOrder:o.sortOrder===null", store)

    def test_legacy_order_actions_are_no_longer_shown_in_preview(self):
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        render_block = orders[orders.index('export function renderOrders'):orders.index('export function clearOrderForm')]
        self.assertNotIn('data-delete-order', render_block)
        self.assertIn('data-order-move', render_block)
        self.assertIn('data-copy-order', render_block)
        self.assertIn('moveOrderByStep(state', orders)
        self.assertIn('data-copy-order', orders)
        self.assertIn("addEventListener('dblclick'", orders)
        self.assertIn('copyOrderAsNew', orders)

    def test_ai_order_recognition_fills_existing_form(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        ai_ui = (ROOT / 'js' / 'orders-ai.js').read_text(encoding='utf-8')
        ai_request = (ROOT / 'js' / 'orders-ai-request.js').read_text(encoding='utf-8')
        self.assertIn('id="aiOrderImage"', view)
        self.assertIn('交貨日期<input id="orderDate"', view)
        self.assertIn('id="billingCustomerInput"', view)
        self.assertIn('id="billingCustomerOptions"', view)
        self.assertIn("fetch('/api/orders/recognize'", ai_request)
        self.assertIn('/api/orders/recognize/status?id=', ai_request)
        self.assertIn('requestOrderRecognition', orders)
        self.assertIn('MAX_NETWORK_FAILURES', ai_request)
        self.assertIn("encoded.length <= 1_800_000", ai_ui)
        self.assertIn("maxDimension = 1600", ai_ui)
        self.assertIn("getImageData", ai_ui)
        self.assertIn("renderAiRecognitionReview", ai_ui)
        self.assertIn('applyRecognizedOrder', orders)
        self.assertIn('id="upstreamInput"', view)
        self.assertIn('id="upstreamOptions"', view)
        self.assertNotIn('syncBillingAndUpstream', orders)
        self.assertIn('billingCustomerInput: billingCustomer, upstreamInput: order.upstream', orders)
        self.assertIn("$('billingCustomerInput')?.addEventListener('input', () => updateOrderSmartHint(state));", orders)
        self.assertIn("$('upstreamInput')?.addEventListener('input', () => updateOrderSmartHint(state));", orders)
        ai_orders = (ROOT / 'api' / 'ai_orders.py').read_text(encoding='utf-8')
        self.assertIn('delivery date / handover date', ai_orders)
        self.assertIn('largest or most prominent full company name', ai_orders)
        self.assertIn('禹利電子分色有限公司 must remain exactly 禹利電子分色有限公司', ai_orders)
        self.assertIn('upstream means the company upstream of 三青', ai_orders)
        self.assertIn('separate from billingCustomer', ai_orders)
        self.assertIn('Read quantity only from the 三青 anchor row', ai_orders)
        self.assertIn('sizeLength maps exactly to 天', ai_orders)
        self.assertIn('normalize_recognized_order', ai_orders)
        self.assertIn('normalize_recognized_order', (ROOT / 'api' / 'service.py').read_text(encoding='utf-8'))
        self.assertIn('reportAiCorrection', orders)
        self.assertIn('id="reportAiCorrectionBtn"', view)
        self.assertIn('syncAddressFromDownstream(state)', orders)
        self.assertIn('送貨地址已使用下游客戶系統地址', orders)
        self.assertIn('送貨地址（下游）', view)
        self.assertIn('/api/orders/recognize/status', (ROOT / 'api' / 'routes.py').read_text(encoding='utf-8'))

    def test_order_form_offers_to_add_unknown_companies(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        order_customers = (ROOT / 'js' / 'orders-customers.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        self.assertIn('id="orderMissingCustomerPrompt"', view)
        self.assertIn('id="addMissingCustomerBtn"', view)
        self.assertIn('id="dismissMissingCustomerBtn"', view)
        self.assertIn("billingCustomerInput: { label: '客人', role: '兩者' }", order_customers)
        self.assertIn("upstreamInput: { label: '上游客戶', role: '上游' }", order_customers)
        self.assertIn("downstreamInput: { label: '下游客戶', role: '下游' }", order_customers)
        self.assertIn('findExactCustomerByName', order_customers)
        self.assertIn('找不到${config.label}', order_customers)
        self.assertIn('目前已停用，要重新啟用嗎', order_customers)
        self.assertIn("state.customers.push({", order_customers)
        self.assertIn("addEventListener('blur', () => updateMissingCustomerPrompt", order_customers)
        self.assertIn('bindMissingCustomerEvents(state, saveState, renderAll)', orders)
        self.assertIn('.order-missing-customer', styles)
        self.assertIn('autocomplete="off" placeholder="通常是工單最上方最大字的公司"', view)
        self.assertNotIn('id="billingCustomerInput" list=', view)
        self.assertNotIn('id="upstreamInput" list=', view)
        self.assertNotIn('id="downstreamInput" list=', view)
        self.assertIn('order-company-suggestions', order_customers)
        self.assertIn("addEventListener('pointerdown'", order_customers)
        self.assertIn("addEventListener('focus'", order_customers)
        self.assertIn("slice(0, 8)", order_customers)
        self.assertIn("event.key === 'ArrowDown'", order_customers)
        self.assertIn('.order-company-suggestions', styles)

    def test_order_quantity_supports_text_and_calculation_value(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn('id="sheetCountText" type="text"', view)
        self.assertIn('id="sheetCount" type="number"', view)
        self.assertIn("sheetCountText: $('sheetCountText').value.trim()", orders)
        self.assertIn("sheetCountText:String(o.sheetCountText??o.sheetCount??'')", store)
        self.assertIn('billingCustomer:String(o.billingCustomer??', store)

    def test_orders_can_be_deleted_and_enter_moves_between_fields(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('data-delete-order', orders)
        self.assertIn('確定要刪除工單', orders)
        self.assertIn("receivable.source === 'auto-order'", orders)
        self.assertIn('id="saveOrderBtn"', view)
        self.assertIn('ORDER_ENTRY_FIELD_IDS', orders)
        self.assertIn('bindOrderEnterNavigation', orders)
        self.assertIn("event.key !== 'Enter'", orders)
        self.assertIn('event.isComposing', orders)
        self.assertIn("linked_receivables", service)

    def test_orders_can_be_reordered_and_copied_as_new(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn('data-order-move', orders)
        self.assertIn('moveOrderByStep(state', orders)
        self.assertNotIn('data-order-drag-handle', orders)
        self.assertIn('data-copy-order', orders)
        self.assertIn("addEventListener('dblclick'", orders)
        self.assertIn('copyOrderAsNew', orders)
        self.assertIn("$('orderNumber').value = ''", orders)
        self.assertIn("$('orderNumber')?.focus()", orders)
        self.assertIn('使用「上移／下移」調整順序', view)
        self.assertIn('autocomplete="off"', view)
        self.assertIn("sortOrder:o.sortOrder===null", store)

    def test_ai_recognition_has_vercel_runtime_limits(self):
        vercel = (ROOT / 'vercel.json').read_text(encoding='utf-8')
        ai_ui = (ROOT / 'js' / 'orders-ai.js').read_text(encoding='utf-8')
        self.assertIn('"maxDuration": 60', vercel)
        self.assertIn('encoded.length <= 1_800_000', ai_ui)


if __name__ == '__main__':
    unittest.main()
