import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class StaticStructureTests(unittest.TestCase):
    def test_health_uses_shared_service(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        vercel_health = (ROOT / 'api' / 'health.py').read_text(encoding='utf-8')
        self.assertIn('from api.service import', flask_server)
        self.assertIn('from api.service import', builtin_server)
        self.assertIn('from api.service import health_payload', vercel_health)

    def test_vercel_users_route_uses_shared_service(self):
        users = (ROOT / 'api' / 'users.py').read_text(encoding='utf-8')
        self.assertIn('from api.service import ApiError, user_action_payload', users)
        self.assertIn('user_action_payload(get_bearer_token(self), read_json_body(self))', users)
        self.assertNotIn('unsupported action', users)

    def test_environment_details_are_not_exposed_by_health_route(self):
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertNotIn('get_environment_status', service)

    def test_configurable_text_is_sanitized(self):
        shared = (ROOT / 'js' / 'shared.js').read_text(encoding='utf-8')
        self.assertIn('sanitizePlainText', shared)
        self.assertIn('merged.moduleLabels = sanitizeMap', shared)
        self.assertIn('merged.moduleIcons = sanitizeMap', shared)

    def test_large_view_is_outside_index(self):
        index = (ROOT / 'index.html').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        loader = (ROOT / 'js' / 'view-loader.js').read_text(encoding='utf-8')
        self.assertNotIn('ordersView', index)
        self.assertIn('ordersView', view)
        self.assertIn("fetch('views/app-shell.html'", loader)
        self.assertNotIn('innerHTML', loader)

    def test_scalable_data_routes_exist_in_both_servers(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        for route in ('/api/bootstrap', '/api/data/', '/api/changes', '/api/reports/summary', '/api/orders/recognize', '/api/orders/recognize/status', '/api/orders/recognize/corrections'):
            self.assertIn(route, flask_server)
            self.assertIn(route, builtin_server)

    def test_admin_clear_test_data_route_exists(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        self.assertIn('/api/admin/clear-test-data', flask_server)
        self.assertIn('/api/admin/clear-test-data', builtin_server)
        self.assertIn('/api/admin/clear-test-data', settings)
        self.assertIn('clearTestDataBtn', view)

    def test_backup_restore_routes_and_controls_exist(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        for route in ('/api/admin/backup', '/api/admin/restore'):
            self.assertIn(route, flask_server)
            self.assertIn(route, builtin_server)
            self.assertIn(route, settings)
        self.assertIn('downloadBackupBtn', view)
        self.assertIn('restoreBackupFile', view)
        self.assertIn('restoreBackupBtn', view)

    def test_capacity_monitor_exists(self):
        flask_server = (ROOT / 'api_server.py').read_text(encoding='utf-8')
        builtin_server = (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('/api/admin/capacity', flask_server)
        self.assertIn('/api/admin/capacity', builtin_server)
        self.assertIn('capacity_payload', service)
        self.assertIn('refreshCapacityBtn', view)
        self.assertIn('capacityMetrics', view)
        self.assertIn('/api/admin/capacity', settings)

    def test_frontend_uses_paged_incremental_storage(self):
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn('pageSize=100', store)
        self.assertIn('/api/changes', store)
        self.assertIn("localStorage.setItem('uiSettings'", store)
        self.assertNotIn("localStorage.setItem('orders'", store)

    def test_login_does_not_wait_for_all_entity_pages(self):
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        self.assertIn('hydrateBootstrap', store)
        self.assertIn('initialPages', store)
        self.assertIn('loadEntityPagesInBackground(missingKeys)', store)
        self.assertIn('bootstrap: data.bootstrap', main)
        self.assertIn('concurrency=2', store)
        self.assertNotIn('await Promise.all(keys.map', store)

    def test_refresh_renders_only_the_active_view(self):
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        render_all = main[main.index('function renderAll()'):main.index('function showView(id)')]
        self.assertIn('switch (activeViewId)', render_all)
        self.assertNotIn('\n  renderDashboard();', render_all)
        self.assertNotIn('\n  renderCustomers(state);', render_all)
        self.assertNotIn('\n  renderSettings(state);', render_all)

    def test_customer_tax_id_is_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        customers = (ROOT / 'js' / 'customers.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        self.assertIn('customerTaxId', view)
        self.assertIn('搜尋名稱/統編/電話/地址', view)
        self.assertIn('normalizeTaxId', customers)
        self.assertIn('taxId = normalizeTaxId', customers)
        self.assertIn('c.taxId ||', customers)
        self.assertIn('normalizeCustomerRole', customers)
        self.assertIn("role === '客人' ? '上游' : role", customers)
        self.assertIn('const billingAndUpstream', customers)
        self.assertIn("['上游', '兩者'].includes(normalizeCustomerRole(c.role))", customers)
        self.assertNotIn("['上游', '客人', '兩者'].includes(c.role)", customers)
        self.assertIn("const upstream = $('upstreamOptions')", customers)
        self.assertIn('billingAndUpstream.forEach((c) => upstream.append', customers)
        self.assertIn('billingAndUpstream.forEach((c) => billing.append', customers)
        self.assertIn("taxId:String(c.taxId??'')", store)
        self.assertIn('invoiceBuyerTaxId', finance)
        self.assertIn('customer?.taxId', finance)

    def test_dashboard_is_compact_and_actionable(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        main = (ROOT / 'js' / 'main.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        self.assertEqual(view.count('data-dashboard-target'), 3)
        self.assertNotIn('dashboardSmartTip', view)
        self.assertNotIn('dashboardHeroTitle', view)
        self.assertIn('summaries = {', main)
        self.assertIn("priority.dataset.dashboardTarget === 'financeView'", main)
        self.assertIn('.dashboard-module-grid { grid-template-columns: repeat(2', styles)

    def test_admin_security_forms_are_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        settings = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
        storage = (ROOT / 'api' / 'storage.py').read_text(encoding='utf-8')
        self.assertIn('createAccountForm', view)
        self.assertIn('financePasswordForm', view)
        self.assertIn('accountPermissionsList', view)
        self.assertIn('value="driver"', view)
        self.assertIn("action: 'create_account'", settings)
        self.assertIn("action: 'update_account_permissions'", settings)
        self.assertIn("action: 'change_finance_password'", settings)
        self.assertIn('allowedViews', settings)
        self.assertIn('allowedViews', storage)
        self.assertIn("hash_password(value)", storage)
        self.assertNotIn('e.currentTarget.reset()', settings)
        settings_close = view.index('</form>', view.index('id="settingsForm"'))
        self.assertGreater(view.index('id="createAccountForm"'), settings_close)
        self.assertGreater(view.index('id="financePasswordForm"'), settings_close)

    def test_finance_quick_actions_are_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        styles = (ROOT / 'styles.css').read_text(encoding='utf-8')
        self.assertIn('financeReceivableActions', view)
        self.assertIn('financePayableActions', view)
        self.assertIn('data-finance-receivable-done', finance)
        self.assertIn('data-finance-payable-done', finance)
        self.assertIn('escapeHtml(value)', finance)
        self.assertIn('.table-actions', styles)

    def test_finance_month_close_and_statement_are_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        self.assertIn('financeCloseMonth', view)
        self.assertIn('statementCustomer', view)
        self.assertIn('exportMonthCloseBtn', view)
        self.assertIn('printCustomerStatementBtn', view)
        self.assertIn('getMonthCloseData', finance)
        self.assertIn('exportCustomerStatement', finance)

    def test_customer_price_rules_are_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        finance = (ROOT / 'js' / 'finance.js').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        records = (ROOT / 'api' / 'records.py').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('priceRuleForm', view)
        self.assertIn('data-order-screen="pricing"', view)
        self.assertIn('openPriceRulesFromOrderBtn', view)
        self.assertIn('priceRuleCustomerMatches', view)
        self.assertNotIn('side-btn" type="button" data-order-screen="pricing"', view)
        self.assertIn('data-order-screen="form">返回新增工單', view)
        self.assertIn('<label>品項 / 上光種類<select id="priceRuleGloss"></select></label>', view)
        self.assertNotIn('id="priceRuleGloss" list="glossOptions"', view)
        self.assertIn('ordersPricingScreen', view)
        self.assertNotIn('data-finance-screen="pricing"', view)
        self.assertNotIn('financePricingScreen', view)
        self.assertIn('priceRulesTbody', view)
        orders_block = view[view.index('id="ordersView"'):view.index('id="customersView"')]
        finance_block = view[view.index('id="financeView"'):view.index('id="auditView"')]
        self.assertIn('priceRuleForm', orders_block)
        self.assertNotIn('priceRuleForm', finance_block)
        self.assertIn('buildPriceRuleFromForm', orders)
        self.assertIn('getPriceRuleCustomerMatches', orders)
        self.assertIn('data-price-rule-customer', orders)
        self.assertIn('customer.taxId', orders)
        self.assertIn("['glossType', 'priceRuleGloss']", orders)
        self.assertIn("'其他'", orders)
        self.assertIn("'其他'", store)
        self.assertIn("activeScreen !== 'pricing'", orders)
        self.assertIn('data-edit-price-rule', orders)
        self.assertNotIn('buildPriceRuleFromForm', finance)
        self.assertIn('calculateOrderQuote', orders)
        self.assertIn('pricingMode', orders)
        self.assertIn('id="machineType"', view)
        self.assertIn('id="priceRuleMachine"', view)
        self.assertIn('客人單價（元／令）', view)
        self.assertIn('settingsPricingDivisor', view)
        self.assertIn('settingsPricingBigMinimum', view)
        self.assertIn("priceRules:'priceRules'", store)
        self.assertIn("'priceRules': 'priceRules'", records)
        self.assertIn("'priceRules':'ordersView'", service)
        self.assertIn('pricing_quote_payload', service)
        self.assertIn('/api/pricing/quote', (ROOT / 'api_server.py').read_text(encoding='utf-8'))

    def test_ai_correction_center_is_present(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('aiCorrectionsTbody', view)
        self.assertIn('refreshAiCorrectionsBtn', view)
        self.assertIn('/api/data/aiCorrections', orders)
        self.assertIn('exportAiCorrections', orders)
        self.assertIn("'aiCorrections':'ordersView'", service)

    def test_ai_order_recognition_fills_existing_form(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        self.assertIn('id="aiOrderImage"', view)
        self.assertIn('交貨日期<input id="orderDate"', view)
        self.assertIn('id="billingCustomerInput"', view)
        self.assertIn('id="billingCustomerOptions"', view)
        self.assertIn("fetch('/api/orders/recognize'", orders)
        self.assertNotIn("fetch('/api/orders/recognize/status'", orders)
        self.assertIn("encoded.length <= 1_600_000", orders)
        self.assertIn("maxDimension = 1280", orders)
        self.assertIn('applyRecognizedOrder', orders)
        self.assertIn('id="upstreamInput"', view)
        self.assertIn('id="upstreamOptions"', view)
        self.assertNotIn('syncBillingAndUpstream', orders)
        self.assertIn('billingCustomerInput: billingCustomer, upstreamInput: order.upstream', orders)
        self.assertIn("$('billingCustomerInput')?.addEventListener('input', () => updateOrderSmartHint(state));", orders)
        self.assertIn("$('upstreamInput')?.addEventListener('input', () => updateOrderSmartHint(state));", orders)
        ai_orders = (ROOT / 'api' / 'ai_orders.py').read_text(encoding='utf-8')
        self.assertIn('delivery date / handover date', ai_orders)
        self.assertIn('upstream vendor is who we bill', ai_orders)
        self.assertIn('Set billingCustomer and upstream to the same value', ai_orders)
        self.assertIn('normalize_recognized_order', ai_orders)
        self.assertIn('normalize_recognized_order', (ROOT / 'api' / 'service.py').read_text(encoding='utf-8'))
        self.assertIn('reportAiCorrection', orders)
        self.assertIn('id="reportAiCorrectionBtn"', view)
        self.assertIn('syncAddressFromDownstream(state)', orders)
        self.assertIn('送貨地址已使用下游客戶系統地址', orders)
        self.assertIn('送貨地址（下游）', view)
        self.assertIn("path=='/api/orders/recognize/status'", (ROOT / 'api' / 'http_server.py').read_text(encoding='utf-8'))

    def test_order_quantity_supports_text_and_calculation_value(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn('id="sheetCountText" type="text"', view)
        self.assertIn('id="sheetCount" type="number"', view)
        self.assertIn("sheetCountText: $('sheetCountText').value.trim()", orders)
        self.assertIn("sheetCountText:String(o.sheetCountText??o.sheetCount??'')", store)
        self.assertIn('billingCustomer:String(o.billingCustomer??', store)

    def test_orders_can_be_deleted_and_enter_moves_between_fields(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        service = (ROOT / 'api' / 'service.py').read_text(encoding='utf-8')
        self.assertIn('data-delete-order', orders)
        self.assertIn('確定要刪除工單', orders)
        self.assertIn("receivable.source === 'auto-order'", orders)
        self.assertIn('id="saveOrderBtn"', view)
        self.assertIn('ORDER_ENTRY_FIELD_IDS', orders)
        self.assertIn('bindOrderEnterNavigation', orders)
        self.assertIn("event.key !== 'Enter'", orders)
        self.assertIn('event.isComposing', orders)
        self.assertIn("linked_receivables", service)

    def test_orders_can_be_reordered_and_copied_as_new(self):
        view = (ROOT / 'views' / 'app-shell.html').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        store = (ROOT / 'js' / 'store.js').read_text(encoding='utf-8')
        self.assertIn('data-move-order', orders)
        self.assertIn('moveOrder(state', orders)
        self.assertIn('data-copy-order', orders)
        self.assertIn("addEventListener('dblclick'", orders)
        self.assertIn('copyOrderAsNew', orders)
        self.assertIn("$('orderNumber').value = ''", orders)
        self.assertIn("$('orderNumber')?.focus()", orders)
        self.assertIn('雙擊複製', view)
        self.assertIn("sortOrder:o.sortOrder===null", store)

    def test_ai_recognition_has_vercel_runtime_limits(self):
        vercel = (ROOT / 'vercel.json').read_text(encoding='utf-8')
        orders = (ROOT / 'js' / 'orders.js').read_text(encoding='utf-8')
        self.assertIn('"maxDuration": 60', vercel)
        self.assertIn('encoded.length <= 1_600_000', orders)


if __name__ == '__main__':
    unittest.main()
